export const affiliateOffersSeed = [
  {
    id: 'aff-admitad-supersim',
    network: 'admitad',
    advertiserId: 'admitad-supersim',
    externalProgramId: 'supersim-program',
    merchantName: 'SuperSim',
    offerSlug: 'supersim-emprestimo-pessoal',
    title: 'Emprestimo pessoal SuperSim',
    category: 'Emprestimos',
    description: 'Uma opcao para quem quer comparar credito pessoal com leitura simples de custos e perfil da oferta.',
    audience: 'Para quem busca emprestimo pessoal com analise rapida e pode precisar de uma opcao mais acessivel.',
    imageUrl: 'https://static.s3.admitad.com/storage-offers-logos/3ea/44c/supersim-logo.png',
    destinationUrl: 'https://www.supersim.com.br/',
    trackingUrl: 'https://ad.admitad.com/g/supersim-placeholder/',
    payoutText: 'Condicoes sujeitas a analise do parceiro',
    ctaText: 'Simular emprestimo',
    disclosureText: 'Se voce avancar por este link, o Cote Juros pode receber comissao sem custo extra para voce.',
    priority: 140,
    productType: 'loan',
    pageSlugs: [
      '/emprestimos',
      '/comparar/emprestimo-online',
      '/emprestimo-online',
      '/emprestimo-online-rapido',
      '/emprestimo-para-negativado',
      '/emprestimo-para-negativado-online',
      '/emprestimo-urgente-hoje',
      '/emprestimo-rapido-pix',
      '/emprestimo-para-autonomo',
      '/emprestimos-para-mei',
      '/supersim-emprestimo',
      '/bancos-digitais-para-credito-rapido',
      '/10-melhores-bancos-para-solicitar-emprestimo',
      '/15-formas-de-conseguir-dinheiro-rapido-opcoes-e-riscos'
    ],
    placements: ['below_hero', 'mid_content', 'before_faq', 'sidebar'],
    metadata: {
      accentColor: '#16A34A',
      secondaryAccentColor: '#0F172A',
      badges: ['Analise rapida', 'Emprestimo pessoal', 'Para negativado']
    }
  },
  {
    id: 'aff-awin-emprestimo-geral',
    network: 'awin',
    advertiserId: 'awin-emprestimo-001',
    merchantName: 'Banco Parceiro Credito',
    offerSlug: 'banco-parceiro-emprestimo',
    title: 'Emprestimo online com analise rapida',
    category: 'Emprestimos',
    description: 'Compare condicoes, prazo e custo total antes de seguir com a contratacao.',
    audience: 'Para quem quer organizar parcelas, ganhar agilidade na analise e entender o custo real do credito.',
    destinationUrl: 'https://www.cotejuros.com.br/emprestimo-online',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Femprestimo-online',
    payoutText: 'Condicoes variam conforme analise',
    ctaText: 'Ver condicoes',
    disclosureText: 'Podemos receber comissao se voce avancar com a contratacao por este link, sem custo extra para voce.',
    priority: 100,
    productType: 'loan',
    pageSlugs: ['/emprestimos', '/comparar/emprestimo-online'],
    placements: ['below_hero', 'mid_content', 'before_faq'],
    metadata: {
      accentColor: '#0F766E',
      secondaryAccentColor: '#0F172A',
      badges: ['Analise rapida', 'Credito online', 'Sem garantia']
    }
  },
  {
    id: 'aff-awin-cartao-sem-anuidade',
    network: 'awin',
    advertiserId: 'awin-cartao-002',
    merchantName: 'Cartao Facil',
    offerSlug: 'cartao-facil-sem-anuidade',
    title: 'Cartao sem anuidade para uso do dia a dia',
    category: 'Cartoes',
    description: 'Veja custo, limite estimado e o que observar antes de pedir o cartao.',
    audience: 'Para quem busca praticidade, custo baixo e leitura clara dos beneficios no uso diario.',
    destinationUrl: 'https://www.cotejuros.com.br/cartao-sem-anuidade',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Fcartao-sem-anuidade',
    payoutText: 'Beneficios e limite sujeitos a analise',
    ctaText: 'Compare opcoes',
    disclosureText: 'Alguns links desta area podem gerar comissao para o Cote Juros, sem alterar o valor final para voce.',
    priority: 95,
    productType: 'credit_card',
    pageSlugs: ['/cartoes-de-credito', '/comparar/cartoes-sem-anuidade'],
    placements: ['below_hero', 'sidebar', 'before_faq'],
    metadata: {
      accentColor: '#1D4ED8',
      secondaryAccentColor: '#0F172A',
      badges: ['Sem anuidade', 'Uso do dia a dia', 'Analise simples']
    }
  },
  {
    id: 'aff-awin-financiamento-veiculo',
    network: 'awin',
    advertiserId: 'awin-financiamento-003',
    merchantName: 'Finance Auto',
    offerSlug: 'finance-auto-veiculo',
    title: 'Financiamento de veiculo com leitura de custo total',
    category: 'Financiamentos',
    description: 'Entenda entrada, prazo e taxa anual antes de comparar propostas.',
    audience: 'Para quem quer avaliar parcelas com mais seguranca antes de assumir um contrato de prazo longo.',
    destinationUrl: 'https://www.cotejuros.com.br/financiamento-veiculo',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Ffinanciamento-veiculo',
    payoutText: 'Condicoes sujeitas a analise do parceiro',
    ctaText: 'Entenda os custos',
    disclosureText: 'Se voce contratar por um link parceiro, o portal pode receber comissao. Isso nao aumenta seu custo.',
    priority: 92,
    productType: 'financing',
    pageSlugs: ['/financiamento'],
    placements: ['below_hero', 'mid_content', 'before_faq'],
    metadata: {
      accentColor: '#B45309',
      secondaryAccentColor: '#0F172A',
      badges: ['Entenda os custos', 'Prazo longo', 'Leitura completa']
    }
  },
  {
    id: 'aff-awin-emprestimo-sidebar',
    network: 'awin',
    advertiserId: 'awin-emprestimo-004',
    merchantName: 'Credito Direto',
    offerSlug: 'credito-direto-pessoal',
    title: 'Veja o que observar antes de contratar credito pessoal',
    category: 'Emprestimos',
    description: 'Uma alternativa para comparar valor liberado, prazo e CET com calma.',
    audience: 'Para quem quer uma leitura objetiva antes de sair do conteudo e seguir para uma analise externa.',
    destinationUrl: 'https://www.cotejuros.com.br/emprestimo-pessoal',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Femprestimo-pessoal',
    payoutText: 'Condicoes variam conforme o perfil',
    ctaText: 'Saiba o que observar antes de contratar',
    disclosureText: 'Os links indicados aqui podem gerar comissao para o portal.',
    priority: 88,
    productType: 'loan',
    pageSlugs: ['/comparar/emprestimo-online', '/emprestimos'],
    placements: ['sidebar'],
    metadata: {
      accentColor: '#0F766E',
      secondaryAccentColor: '#14532D',
      badges: ['Credito pessoal', 'Boa leitura', 'Condicoes claras']
    }
  },
  {
    id: 'aff-awin-cartao-inline',
    network: 'awin',
    advertiserId: 'awin-cartao-005',
    merchantName: 'Cartao Beneficios',
    offerSlug: 'cartao-beneficios-cashback',
    title: 'Cartao com beneficios para quem quer controlar melhor a fatura',
    category: 'Cartoes',
    description: 'Compare anuidade, beneficios e criterios de aprovacao com mais contexto.',
    audience: 'Para quem quer entender se o beneficio compensa no uso real e manter a fatura sob controle.',
    destinationUrl: 'https://www.cotejuros.com.br/cartao-com-cashback',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Fcartao-com-cashback',
    payoutText: 'Beneficios sujeitos a analise do emissor',
    ctaText: 'Ver condicoes',
    disclosureText: 'Pode haver remuneracao por indicacao nos links desta secao.',
    priority: 85,
    productType: 'credit_card',
    pageSlugs: ['/cartoes-de-credito', '/comparar/cartoes-sem-anuidade'],
    placements: ['mid_content'],
    metadata: {
      accentColor: '#7C3AED',
      secondaryAccentColor: '#0F172A',
      badges: ['Cashback', 'Comparacao rapida', 'Perfil do dia a dia']
    }
  }
];
