export const affiliateOffersSeed = [
  {
    id: 'aff-awin-emprestimo-geral',
    network: 'awin',
    advertiserId: 'awin-emprestimo-001',
    merchantName: 'Banco Parceiro Crédito',
    offerSlug: 'banco-parceiro-emprestimo',
    title: 'Empréstimo online com análise rápida',
    category: 'Empréstimos',
    description: 'Compare condições, prazo e custo total antes de seguir com a contratação.',
    audience: 'Para quem quer organizar parcelas e entender o custo real do crédito.',
    destinationUrl: 'https://www.cotejuros.com.br/emprestimo-online',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Femprestimo-online',
    ctaText: 'Ver condições',
    disclosureText: 'Podemos receber comissão se você avançar com a contratação por este link, sem custo extra para você.',
    priority: 100,
    productType: 'loan',
    pageSlugs: ['/emprestimos', '/comparar/emprestimo-online'],
    placements: ['below_hero', 'mid_content', 'before_faq']
  },
  {
    id: 'aff-awin-cartao-sem-anuidade',
    network: 'awin',
    advertiserId: 'awin-cartao-002',
    merchantName: 'Cartão Fácil',
    offerSlug: 'cartao-facil-sem-anuidade',
    title: 'Cartão sem anuidade para uso do dia a dia',
    category: 'Cartões',
    description: 'Veja custo, limite estimado e o que observar antes de pedir o cartão.',
    audience: 'Para quem busca praticidade, custo baixo e leitura clara dos benefícios.',
    destinationUrl: 'https://www.cotejuros.com.br/cartao-sem-anuidade',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Fcartao-sem-anuidade',
    ctaText: 'Compare opções',
    disclosureText: 'Alguns links desta área podem gerar comissão para o Cote Juros, sem alterar o valor final para você.',
    priority: 95,
    productType: 'credit_card',
    pageSlugs: ['/cartoes-de-credito', '/comparar/cartoes-sem-anuidade'],
    placements: ['below_hero', 'sidebar', 'before_faq']
  },
  {
    id: 'aff-awin-financiamento-veiculo',
    network: 'awin',
    advertiserId: 'awin-financiamento-003',
    merchantName: 'Finance Auto',
    offerSlug: 'finance-auto-veiculo',
    title: 'Financiamento de veículo com leitura de custo total',
    category: 'Financiamentos',
    description: 'Entenda entrada, prazo e taxa anual antes de comparar propostas.',
    audience: 'Para quem quer avaliar parcelas com mais segurança antes de assumir contrato longo.',
    destinationUrl: 'https://www.cotejuros.com.br/financiamento-veiculo',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Ffinanciamento-veiculo',
    ctaText: 'Entenda os custos',
    disclosureText: 'Se você contratar por um link parceiro, o portal pode receber comissão. Isso não aumenta seu custo.',
    priority: 92,
    productType: 'financing',
    pageSlugs: ['/financiamento'],
    placements: ['below_hero', 'mid_content', 'before_faq']
  },
  {
    id: 'aff-awin-emprestimo-sidebar',
    network: 'awin',
    advertiserId: 'awin-emprestimo-004',
    merchantName: 'Crédito Direto',
    offerSlug: 'credito-direto-pessoal',
    title: 'Veja o que observar antes de contratar crédito pessoal',
    category: 'Empréstimos',
    description: 'Uma alternativa para comparar valor liberado, prazo e CET com calma.',
    audience: 'Para quem quer uma leitura objetiva antes de sair do conteúdo.',
    destinationUrl: 'https://www.cotejuros.com.br/emprestimo-pessoal',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Femprestimo-pessoal',
    ctaText: 'Saiba o que observar antes de contratar',
    disclosureText: 'Os links indicados aqui podem gerar comissão para o portal.',
    priority: 88,
    productType: 'loan',
    pageSlugs: ['/comparar/emprestimo-online', '/emprestimos'],
    placements: ['sidebar']
  },
  {
    id: 'aff-awin-cartao-inline',
    network: 'awin',
    advertiserId: 'awin-cartao-005',
    merchantName: 'Cartão Benefícios',
    offerSlug: 'cartao-beneficios-cashback',
    title: 'Cartão com benefícios para quem quer controlar melhor a fatura',
    category: 'Cartões',
    description: 'Compare anuidade, benefícios e critérios de aprovação com mais contexto.',
    audience: 'Para quem quer entender se o benefício compensa no uso real.',
    destinationUrl: 'https://www.cotejuros.com.br/cartao-com-cashback',
    trackingUrl: 'https://www.awin1.com/cread.php?awinmid=00000&awinaffid=000000&ued=https%3A%2F%2Fwww.cotejuros.com.br%2Fcartao-com-cashback',
    ctaText: 'Ver condições',
    disclosureText: 'Pode haver remuneração por indicação nos links desta seção.',
    priority: 85,
    productType: 'credit_card',
    pageSlugs: ['/cartoes-de-credito', '/comparar/cartoes-sem-anuidade'],
    placements: ['mid_content']
  }
];
